import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar follows the folder structure of docs/. The pages below
// platform/, bsp/ and artifacts/ are generated by scripts/sync-docs.mjs from the
// repository names (Bsp-Mcal-Exti -> bsp/mcal/exti), see its header.
const sidebars: SidebarsConfig = {
    docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
