import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docs: [
        'intro',
        {
            type: 'category',
            label: 'Platform',
            items: [{type: 'autogenerated', dirName: 'platform'}],
        },
        {
            type: 'category',
            label: 'BSP',
            items: [{type: 'autogenerated', dirName: 'bsp'}],
        },
        {
            type: 'category',
            label: 'Artifacts',
            items: [{type: 'autogenerated', dirName: 'artifacts'}],
        },
    ],
};

export default sidebars;
