#!/usr/bin/env node
/**
 * Pulls README.md files from the Embedbits GitHub repositories and writes them
 * into docs/ as Docusaurus pages.
 *
 *   npm run sync-docs
 *
 * The generated pages are committed, so the site builds offline. Re-run the
 * script whenever a README changes. Do not edit generated pages by hand --
 * change the README in the source repository instead.
 *
 * Every documented repository is scanned for further README.md files below its
 * root. When it has any, its main page becomes a sidebar category (index page)
 * and the other READMEs are listed beneath it.
 */
import {mkdir, readdir, readFile, rm, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ORG = 'Embedbits';

// Repositories that never get a documentation page.
const IGNORE = new Set(['Web']);
const DOCS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../docs');

// Pages with a hand-picked title, location or sidebar position.
// dir = folder under docs/, file = page name, position = sidebar order,
// source = file in the repository (default README.md),
// replace = [regex, replacement] pairs applied to the Markdown source.
// Repositories that are not listed here are discovered automatically, see
// discoverPages().
const KNOWN_PAGES = [
  // Platform
  {
    repo: 'EmBi_Platform', dir: 'platform', file: 'embi-platform', title: 'EmBi_Platform', position: 1,
    replace: [[/ \(STM_Template\)/g, '']],
  },
  {repo: 'EmBi-ArtifactsHandler', dir: 'platform', file: 'artifacts-handler', title: 'Artifacts Handler', position: 2},
  {
    repo: 'EmBi_Platform', source: 'Coding_Style.md', dir: 'platform', file: 'coding-style', title: 'Coding Style', position: 1,
    parent: 'EmBi_Platform',
    // The source links to a wiki page that does not exist in the repository.
    replace: [[/\[[^\]]*File Organization\]\(\.\/File_Organization\)/, 'File Organization (separate wiki page)']],
  },

  // BSP
  {repo: 'Bsp', dir: 'bsp', file: 'overview', title: 'BSP Overview', label: 'Overview', position: 1},
  {repo: 'Bsp-Linker', dir: 'bsp', file: 'linker', title: 'Linker', position: 2},
  {repo: 'Bsp-Startup', dir: 'bsp', file: 'startup', title: 'Startup', position: 3},
  {repo: 'Bsp-Docs', dir: 'bsp', file: 'docs-module', title: 'Docs Module', position: 4},

  // RAL
  {repo: 'Bsp-Ral', dir: 'bsp/ral', file: 'overview', title: 'RAL Overview', label: 'Overview', position: 1},
  {repo: 'Bsp-Ral-CMSIS', dir: 'bsp/ral', file: 'cmsis', title: 'RAL CMSIS', label: 'CMSIS', position: 2},
  {repo: 'Bsp-Ral-CMSIS_ST', dir: 'bsp/ral', file: 'cmsis-st', title: 'RAL CMSIS ST', label: 'CMSIS ST', position: 3},
  {repo: 'Bsp-Ral-RAL_ST', dir: 'bsp/ral', file: 'ral-st', title: 'RAL ST', label: 'RAL ST', position: 4},

  // MCAL
  {repo: 'Bsp-Mcal', dir: 'bsp/mcal', file: 'overview', title: 'MCAL Overview', label: 'Overview', position: 1},
  ...[
    ['Core', 'Core'], ['Rcc', 'RCC'], ['Gpio', 'GPIO'], ['Exti', 'EXTI'], ['Nvic', 'NVIC'],
    ['Tim', 'TIM'], ['Usart', 'USART'], ['I2c', 'I2C'], ['Adc', 'ADC'], ['Crc', 'CRC'],
    ['Rng', 'RNG'], ['Iwdg', 'IWDG'], ['Dma', 'DMA'], ['Gpdma', 'GPDMA'],
  ].map(([name, label], i) => ({
    repo: `Bsp-Mcal-${name}`, dir: 'bsp/mcal/modules', file: name.toLowerCase(),
    title: `${label} MCAL Module`, label, position: i + 1,
  })),

  // Artifacts
  {repo: 'Artifacts', dir: 'artifacts', file: 'overview', title: 'Artifacts Overview', label: 'Overview', position: 1},
  ...[
    ['gcc', 'gcc'], ['gcc_arm_none_eabi', 'gcc-arm-none-eabi'], ['ninja', 'Ninja'], ['doxygen', 'Doxygen'],
    ['graphviz', 'Graphviz'], ['python', 'Python'], ['ruby', 'Ruby'], ['unity', 'Unity'],
    ['cmock', 'CMock'], ['renode', 'Renode'], ['probe_rs', 'probe-rs'], ['u8g2', 'u8g2'],
  ].map(([name, label], i) => ({
    repo: `Artifact-${name}`, dir: 'artifacts/tools', file: name.replace(/_/g, '-'),
    title: `${label} Artifact`, label, position: i + 1,
  })),
];

// Naming conventions used for automatically discovered repositories.
// Discovered pages are placed after the known ones, in alphabetical order.
const RULES = [
  {prefix: 'Bsp-Mcal-', dir: 'bsp/mcal/modules', label: (n) => n.toUpperCase(), title: (l) => `${l} MCAL Module`},
  {prefix: 'Bsp-Ral-', dir: 'bsp/ral', label: (n) => n.replace(/_/g, ' '), title: (l) => `RAL ${l}`},
  {prefix: 'Artifact-', dir: 'artifacts/tools', label: (n) => n.replace(/_/g, '-'), title: (l) => `${l} Artifact`},
];

// README.md files in these directories are never documented (dependencies, build output, ...).
const EXCLUDED_DIR = /(^|\/)(\.[^/]+|node_modules|build|dist|out|third[_-]?party|external|vendor|submodules?)(\/|$)/i;

const GENERATED_MARKER = 'Generated by scripts/sync-docs.mjs';

/** Lists the repositories of the organization (needs GITHUB_TOKEN in CI to avoid rate limits). */
async function listRepos() {
  const headers = {Accept: 'application/vnd.github+json', 'User-Agent': 'embedbits-sync-docs'};
  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;
  const names = [];
  for (let page = 1; ; page++) {
    const res = await fetch(`https://api.github.com/orgs/${ORG}/repos?per_page=100&page=${page}`, {headers});
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const batch = await res.json();
    names.push(...batch.filter((r) => !r.archived).map((r) => r.name));
    if (batch.length < 100) return names;
  }
}

/** Lists the paths of all files in a repository; throws when the list is unavailable or truncated. */
async function listFiles(repo) {
  const headers = {Accept: 'application/vnd.github+json', 'User-Agent': 'embedbits-sync-docs'};
  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;
  const res = await fetch(`https://api.github.com/repos/${ORG}/${repo}/git/trees/HEAD?recursive=1`, {headers});
  if (res.status === 409) return []; // empty repository
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const tree = await res.json();
  if (tree.truncated) throw new Error('file list truncated');
  return tree.tree.filter((e) => e.type === 'blob').map((e) => e.path);
}

/** Returns the README.md files below the root of a repository as {dir, file}, sorted by directory. */
function nestedReadmes(files) {
  return files
    .filter((f) => /\/README\.md$/i.test(f))
    .map((file) => ({file, dir: file.slice(0, file.lastIndexOf('/'))}))
    .filter(({dir}) => !EXCLUDED_DIR.test(dir))
    .sort((a, b) => a.dir.localeCompare(b.dir));
}

/** Returns the known pages plus pages for new repositories that match a naming rule. */
async function discoverPages() {
  let repos;
  try {
    repos = await listRepos();
  } catch (err) {
    console.warn(`Could not list ${ORG} repositories (${err.message}); using the known pages only.`);
    return KNOWN_PAGES;
  }
  const known = new Set(KNOWN_PAGES.map((p) => p.repo));
  const pages = [...KNOWN_PAGES];
  const unmatched = [];
  for (const repo of repos.sort((a, b) => a.localeCompare(b))) {
    if (known.has(repo) || IGNORE.has(repo)) continue;
    const rule = RULES.find((r) => repo.startsWith(r.prefix));
    if (!rule) {
      unmatched.push(repo);
      continue;
    }
    const name = repo.slice(rule.prefix.length);
    const label = rule.label(name);
    const position = 100 + pages.filter((p) => p.dir === rule.dir).length;
    pages.push({repo, dir: rule.dir, file: name.toLowerCase().replace(/_/g, '-'), title: rule.title(label), label, position});
    console.log(`New repository found: ${repo} -> docs/${rule.dir}`);
  }
  if (unmatched.length) {
    console.log(`Not documented (no naming rule, add to KNOWN_PAGES to include): ${unmatched.join(', ')}`);
  }
  // Repositories that were deleted, renamed or archived lose their page.
  const gone = pages.filter((p) => !repos.includes(p.repo)).map((p) => p.repo);
  if (gone.length) console.warn(`Repositories no longer in the organization, pages dropped: ${gone.join(', ')}`);
  return pages.filter((p) => repos.includes(p.repo));
}

/** Deletes generated pages whose source repository is gone or has no README any more. */
async function removeStale(keep) {
  const walk = async (dir) => {
    for (const entry of await readdir(dir, {withFileTypes: true})) {
      const file = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(file);
        if ((await readdir(file)).length === 0) await rm(file, {recursive: true});
      }
      else if (entry.name.endsWith('.md') && !keep.has(file) && (await readFile(file, 'utf8')).includes(GENERATED_MARKER)) {
        await rm(file);
        console.log(`Removed stale page ${path.relative(DOCS, file)}`);
      }
    }
  };
  await walk(DOCS);
}

/** Drops `## <heading>` sections whose heading matches `test`. */
function dropSections(md, test) {
  const lines = md.split('\n');
  const out = [];
  let skipping = false;
  let inFence = false;
  for (const line of lines) {
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    const heading = !inFence && /^##\s+(.*)$/.exec(line);
    if (heading) skipping = test(heading[1]);
    if (!skipping) out.push(line);
  }
  return out.join('\n');
}

function rewriteLinks(md, repo, baseDir = '') {
  const blob = `https://github.com/${ORG}/${repo}/blob/HEAD/`;
  const raw = `https://raw.githubusercontent.com/${ORG}/${repo}/HEAD/`;
  const isRelative = (u) => !/^([a-z][a-z0-9+.-]*:|#|\/\/)/i.test(u);
  // Resolves a link relative to the directory of the README it appears in.
  const clean = (u) => path.posix.normalize(path.posix.join(baseDir, u)).replace(/^\.\//, '');
  return md
    .replace(/(!\[[^\]]*\]\()([^)\s]+)(\))/g, (m, a, u, b) => (isRelative(u) ? a + raw + clean(u) + b : m))
    .replace(/(\[[^\]]*\]\()([^)\s]+)(\))/g, (m, a, u, b) => (isRelative(u) ? a + blob + clean(u) + b : m));
}

function transform(md, repo, replace = [], baseDir = '') {
  let body = md.replace(/\r\n/g, '\n').replace(/^﻿/, '').trim();
  for (const [pattern, replacement] of replace) body = body.replace(pattern, replacement);
  body = body.replace(/^# .*\n+/, ''); // title comes from front matter
  body = dropSections(body, (h) => /table of contents|useful links/i.test(h));
  body = rewriteLinks(body, repo, baseDir);
  body = body.replace(/\n(\s*---\s*\n){2,}/g, '\n---\n').replace(/\n{3,}/g, '\n\n');
  return body.trim() + '\n';
}

async function fetchReadme(repo, source = 'README.md') {
  const res = await fetch(`https://raw.githubusercontent.com/${ORG}/${repo}/HEAD/${source}`);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`${repo}: HTTP ${res.status}`);
  return res.text();
}

const PAGES = await discoverPages();

// Work out where each page is written. A repository with further READMEs (or
// with pages that declare it as `parent`) becomes a folder whose main page is
// index.md, so Docusaurus turns it into a sidebar category linking to that page.
let complete = true; // false when a file list was unavailable; stale pages are then kept
const outputs = [];
await Promise.all(
  PAGES.filter((p) => !p.source).map(async (p) => {
    let readmes;
    try {
      readmes = nestedReadmes(await listFiles(p.repo));
    } catch (err) {
      console.warn(`Could not list files of ${p.repo} (${err.message}); keeping its pages as they are.`);
      complete = false;
      return;
    }
    const hasChildren = readmes.length > 0 || PAGES.some((c) => c.parent === p.repo);
    const folder = `${p.dir}/${p.file}`;
    outputs.push({...p, dir: hasChildren ? folder : p.dir, file: hasChildren ? 'index' : p.file, folder: hasChildren ? folder : null});
    readmes.forEach(({dir, file: source}, i) => {
      outputs.push({
        repo: p.repo, source, baseDir: dir, dir: folder,
        file: dir.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''),
        title: dir, label: dir.split('/').pop(), position: 10 + i, fromTree: true,
      });
    });
  }),
);
for (const p of PAGES.filter((c) => c.source)) {
  const parent = outputs.find((o) => o.repo === p.parent && o.folder);
  if (p.parent && !parent) continue; // parent not listed (see warning above) -> leave the page untouched
  outputs.push({...p, dir: parent ? parent.folder : p.dir});
}

const written = new Set();
const missing = [];
await Promise.all(
  outputs.map(async (p) => {
    const readme = await fetchReadme(p.repo, p.source);
    if (readme === null) return missing.push(p.fromTree ? `${p.repo}/${p.source}` : p.repo);
    let {title, label} = p;
    if (p.fromTree) {
      // Prefer the first heading of the README over the bare directory name.
      const heading = /^#\s+(.+?)\s*#*\s*$/m.exec(readme.replace(/\r\n/g, '\n'));
      if (heading) title = label = heading[1].replace(/[`*_]/g, '').trim();
    }
    const front = [
      '---',
      `title: ${JSON.stringify(title)}`,
      `sidebar_label: ${JSON.stringify(label ?? title)}`,
      `sidebar_position: ${p.position}`,
      `custom_edit_url: https://github.com/${ORG}/${p.repo}/edit/HEAD/${p.source ?? 'README.md'}`,
      '---',
      '',
      `{/* ${GENERATED_MARKER} from ${ORG}/${p.repo}. Do not edit here. */}`,
      '',
    ].join('\n');
    const dir = path.join(DOCS, p.dir);
    await mkdir(dir, {recursive: true});
    written.add(path.join(dir, `${p.file}.md`));
    // .md files are parsed as CommonMark (see markdown.format in docusaurus.config.ts),
    // so the MDX comment is replaced by a plain HTML comment.
    await writeFile(
      path.join(dir, `${p.file}.md`),
      front.replace(/\{\/\*(.*)\*\/\}/, '<!--$1-->') + transform(readme, p.repo, p.replace, p.baseDir),
    );
  }),
);

if (complete) await removeStale(written);
else console.warn('Stale pages were not removed because some file lists were unavailable.');

console.log(`Synced ${outputs.length - missing.length} pages.`);
if (missing.length) console.log(`No README found for: ${missing.join(', ')}`);
