#!/usr/bin/env node
/**
 * Pulls README.md files from the Embedbits GitHub repositories and writes them
 * into docs/ as Docusaurus pages.
 *
 *   npm run sync-docs
 *
 * The generated pages are committed, so the site builds offline. Re-run the
 * script whenever a README changes. Do not edit generated pages by hand --
 * change the README in the source repository instead.
 *
 * Layout
 * ------
 * The sidebar mirrors the hierarchical repository names: `Bsp-Mcal-Exti` is the
 * module Exti of the Mcal layer of the Bsp layer and ends up in
 * docs/bsp/mcal/exti.md. A repository that has children (other repositories
 * below its name or further README.md files in its tree) is written as
 * index.md of a folder, which Docusaurus renders as an expandable category.
 * Name segments without a repository of their own become plain categories.
 *
 * STM32 families
 * --------------
 * Repositories keep one branch per STM32 family (STM32G4, STM32H5, ...). Every
 * page of such a repository starts with the families it supports (and the ones
 * that exist in the organization but not here), and the pages of a layer get a
 * table that shows which module supports which family.
 *
 * If anything needed for the layout cannot be loaded (GitHub API error, rate
 * limit, ...) the whole sync is skipped and the committed pages stay untouched.
 */
import {execFile} from 'node:child_process';
import {mkdir, readdir, readFile, rm, writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {promisify} from 'node:util';

const run = promisify(execFile);

const ORG = 'Embedbits';

// Repositories that never get a documentation page.
const IGNORE = new Set(['Web']);
const DOCS = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../docs');

// Position of a repository in the hierarchy when its name does not describe it.
const PATHS = {
  EmBi_Platform: ['Platform', 'EmBi_Platform'],
  'EmBi-ArtifactsHandler': ['Platform', 'Artifacts-Handler'],
};

// First name segment -> segment used in the hierarchy (Artifact-gcc lives below Artifacts).
const ALIASES = {Artifact: 'Artifacts'};

// Sidebar order of sibling segments; everything else follows alphabetically.
const ORDER = [
  'Platform', 'Bsp', 'Artifacts',
  'EmBi_Platform', 'Artifacts-Handler',
  'Linker', 'Startup', 'Docs', 'Ral', 'Mcal',
  'CMSIS', 'CMSIS_ST', 'RAL_ST',
  'Core', 'Rcc', 'Gpio', 'Exti', 'Nvic', 'Tim', 'Usart', 'I2c', 'Spi', 'Adc', 'Dac', 'Crc', 'Rng', 'Iwdg',
  'Dma', 'Gpdma', 'Dma2D',
  'gcc', 'gcc_arm_none_eabi', 'ninja', 'doxygen', 'graphviz', 'python', 'ruby', 'unity', 'cmock', 'renode',
  'probe_rs', 'u8g2',
];

// Sidebar labels that cannot be derived from the segment (see labelOf()).
const LABELS = {
  Bsp: 'BSP', Mcal: 'MCAL', Ral: 'RAL', 'Artifacts-Handler': 'Artifacts Handler', Core: 'Core',
  ninja: 'Ninja', doxygen: 'Doxygen', graphviz: 'Graphviz', python: 'Python', ruby: 'Ruby', unity: 'Unity',
  cmock: 'CMock', renode: 'Renode',
};

// Page titles of repositories that introduce a layer.
const TITLES = {
  Bsp: 'BSP Overview', 'Bsp-Mcal': 'MCAL Overview', 'Bsp-Ral': 'RAL Overview', Artifacts: 'Artifacts Overview',
};

// Per repository: `replace` = [regex, replacement] pairs applied to the README,
// `files` = further Markdown files (not named README.md) that are documented below the README
// (each with its own `replace` and `replaceAfter`).
const REPO_OPTIONS = {
  EmBi_Platform: {
    replace: [[/ \(STM_Template\)/g, '']],
    files: [
      {
        source: 'Coding_Style.md', file: 'coding-style', title: 'Coding Style',
        // The source links to a wiki page that does not exist in the repository, the topic has an article.
        // replaceAfter runs after the relative links were rewritten to GitHub URLs, so a site link stays a site link.
        replace: [[/\[[^\]]*File Organization\]\(\.\/File_Organization\)/, 'FILE_ORGANIZATION_LINK']],
        replaceAfter: [['FILE_ORGANIZATION_LINK', '[File Organization](/blog/file-organization-embedded-c)']],
      },
    ],
  },
};

// README.md files in these directories are never documented (dependencies, build output, ...).
const EXCLUDED_DIR = /(^|\/)(\.[^/]+|node_modules|build|dist|out|third[_-]?party|external|vendor|submodules?)(\/|$)/i;

// Branches that name an STM32 family, e.g. STM32G4 (release branches such as STM32G4_1.x are not families).
const FAMILY_BRANCH = /^STM32[A-Z]\d+$/i;

const GENERATED_MARKER = 'Generated by scripts/sync-docs.mjs';

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

function apiHeaders() {
  const headers = {Accept: 'application/vnd.github+json', 'User-Agent': 'embedbits-sync-docs'};
  const token = process.env.GITHUB_TOKEN ?? process.env.GH_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;
  return headers;
}

/**
 * Lists the repositories of the account (needs GITHUB_TOKEN in CI to avoid rate limits).
 * ORG can be an organization or a user account, the API has a separate endpoint for each.
 */
async function listRepos() {
  for (const kind of ['orgs', 'users']) {
    const names = [];
    for (let page = 1; ; page++) {
      const res = await fetch(`https://api.github.com/${kind}/${ORG}/repos?per_page=100&page=${page}`, {headers: apiHeaders()});
      if (res.status === 404 && kind === 'orgs') break; // not an organization, try the user endpoint
      if (!res.ok) throw new Error(`repository listing: HTTP ${res.status}`);
      const batch = await res.json();
      names.push(...batch.filter((r) => !r.archived).map((r) => r.name));
      if (batch.length < 100) return names;
    }
  }
  throw new Error(`repository listing: ${ORG} not found`);
}

/** Lists the paths of all files in a repository. */
async function listFiles(repo) {
  const res = await fetch(`https://api.github.com/repos/${ORG}/${repo}/git/trees/HEAD?recursive=1`, {headers: apiHeaders()});
  if (res.status === 409) return []; // empty repository
  if (!res.ok) throw new Error(`${repo} file list: HTTP ${res.status}`);
  const tree = await res.json();
  if (tree.truncated) throw new Error(`${repo} file list: truncated`);
  return tree.tree.filter((e) => e.type === 'blob').map((e) => e.path);
}

/** Returns the STM32 families a repository has a branch for, e.g. ['STM32G4', 'STM32H5']. */
async function listFamilies(repo) {
  let stdout;
  for (let attempt = 1; ; attempt++) {
    try {
      ({stdout} = await run('git', ['ls-remote', '--heads', `https://github.com/${ORG}/${repo}`], {timeout: 60_000}));
      break;
    } catch (err) {
      if (attempt === 3) throw new Error(`${repo} branch list: ${err.message.split('\n')[0]}`);
      await new Promise((resolve) => setTimeout(resolve, 2000 * attempt));
    }
  }
  return stdout
      .split('\n')
      .map((line) => line.split('\t')[1]?.replace('refs/heads/', ''))
      .filter((b) => b && FAMILY_BRANCH.test(b))
      .map((b) => b.toUpperCase())
      .sort(naturalCompare);
}

/** Like Promise.all(items.map(fn)) but with at most `limit` calls running at the same time. */
async function mapLimit(items, limit, fn) {
  const results = new Array(items.length);
  let next = 0;
  await Promise.all(
    Array.from({length: Math.min(limit, items.length)}, async () => {
      while (next < items.length) {
        const i = next++;
        results[i] = await fn(items[i]);
      }
    }),
  );
  return results;
}

function naturalCompare(a, b) {
  return a.localeCompare(b, 'en', {numeric: true});
}

/** Returns the README.md files below the root of a repository as {dir, file}, sorted by directory. */
function nestedReadmes(files) {
  return files
    .filter((f) => /\/README\.md$/i.test(f))
    .map((file) => ({file, dir: file.slice(0, file.lastIndexOf('/'))}))
    .filter(({dir}) => !EXCLUDED_DIR.test(dir))
    .sort((a, b) => a.dir.localeCompare(b.dir));
}

/** Position of a repository in the documentation hierarchy, e.g. Bsp-Mcal-Exti -> [Bsp, Mcal, Exti]. */
function segmentsOf(repo) {
  if (PATHS[repo]) return PATHS[repo];
  const parts = repo.split('-');
  parts[0] = ALIASES[parts[0]] ?? parts[0];
  return parts;
}

function labelOf(segments) {
  const seg = segments[segments.length - 1];
  if (LABELS[seg]) return LABELS[seg];
  const parent = segments[segments.length - 2];
  if (parent === 'Mcal' || parent === 'Ral') return seg.replace(/_/g, ' ').toUpperCase();
  if (parent === 'Artifacts') return seg.replace(/_/g, '-');
  return seg.replace(/_/g, ' ');
}

function titleOf(node) {
  if (node.repo && TITLES[node.repo]) return TITLES[node.repo];
  const parent = node.segments[node.segments.length - 2];
  if (parent === 'Mcal') return `${node.label} MCAL Module`;
  if (parent === 'Ral') return `RAL ${node.label}`;
  if (parent === 'Artifacts') return `${node.label} Artifact`;
  return node.label;
}

/** Builds the tree of pages from the repository names. */
function buildTree(repos) {
  const nodes = new Map(); // key (slugs joined with /) -> node
  const get = (segments) => {
    const key = segments.map(slug).join('/');
    let node = nodes.get(key);
    if (!node) {
      node = {key, segments, label: labelOf(segments), repo: null, children: [], nested: [], files: []};
      nodes.set(key, node);
      if (segments.length > 1) get(segments.slice(0, -1)).children.push(node);
    }
    return node;
  };
  for (const info of repos) get(segmentsOf(info.repo)).repo = info.repo;
  return {nodes, get};
}

/** Deletes generated pages that were not written this time (repository removed, README gone, layout changed). */
async function removeStale(keep) {
  const walk = async (dir) => {
    for (const entry of await readdir(dir, {withFileTypes: true})) {
      const file = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(file);
        if ((await readdir(file)).length === 0) await rm(file, {recursive: true});
      } else if (keep.has(file)) {
        continue;
      } else if (entry.name === '_category_.json') {
        await rm(file); // only this script writes category files
        console.log(`Removed stale category ${path.relative(DOCS, file)}`);
      } else if (entry.name.endsWith('.md') && (await readFile(file, 'utf8')).includes(GENERATED_MARKER)) {
        await rm(file);
        console.log(`Removed stale page ${path.relative(DOCS, file)}`);
      }
    }
  };
  await walk(DOCS);
}

/** Drops `## <heading>` sections whose heading matches `test`. */
function dropSections(md, test) {
  const lines = md.split('\n');
  const out = [];
  let skipping = false;
  let inFence = false;
  for (const line of lines) {
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    const heading = !inFence && /^##\s+(.*)$/.exec(line);
    if (heading) skipping = test(heading[1]);
    if (!skipping) out.push(line);
  }
  return out.join('\n');
}

function rewriteLinks(md, repo, baseDir = '') {
  const blob = `https://github.com/${ORG}/${repo}/blob/HEAD/`;
  const raw = `https://raw.githubusercontent.com/${ORG}/${repo}/HEAD/`;
  const isRelative = (u) => !/^([a-z][a-z0-9+.-]*:|#|\/\/)/i.test(u);
  // Resolves a link relative to the directory of the README it appears in.
  const clean = (u) => path.posix.normalize(path.posix.join(baseDir, u)).replace(/^\.\//, '');
  return md
    .replace(/(!\[[^\]]*\]\()([^)\s]+)(\))/g, (m, a, u, b) => (isRelative(u) ? a + raw + clean(u) + b : m))
    .replace(/(\[[^\]]*\]\()([^)\s]+)(\))/g, (m, a, u, b) => (isRelative(u) ? a + blob + clean(u) + b : m));
}

function transform(md, repo, replace = [], baseDir = '', replaceAfter = []) {
  let body = md.replace(/\r\n/g, '\n').replace(/^﻿/, '').trim();
  for (const [pattern, replacement] of replace) body = body.replace(pattern, replacement);
  body = body.replace(/^# .*\n+/, ''); // title comes from front matter
  body = dropSections(body, (h) => /table of contents|useful links/i.test(h));
  body = rewriteLinks(body, repo, baseDir);
  for (const [pattern, replacement] of replaceAfter) body = body.replace(pattern, replacement);
  body = body.replace(/\n(\s*---\s*\n){2,}/g, '\n---\n').replace(/\n{3,}/g, '\n\n');
  return body.trim() + '\n';
}

async function fetchReadme(repo, source = 'README.md') {
  const res = await fetch(`https://raw.githubusercontent.com/${ORG}/${repo}/HEAD/${source}`);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`${repo}: HTTP ${res.status}`);
  return res.text();
}

const familyName = (f) => f.replace(/^STM32/i, '');

/** One-line summary of the supported (and missing) families, shown at the top of a repository page. */
function familyBanner(repo, families, allFamilies) {
  if (!families.length) return '';
  const link = (f) => `[${familyName(f)}](https://github.com/${ORG}/${repo}/tree/${f})`;
  const missing = allFamilies.filter((f) => !families.includes(f));
  const lines = [`**Supported STM32 families:** ${families.map(link).join(' · ')}`];
  if (missing.length) lines.push(`**Not supported:** ${missing.map(familyName).join(', ')}`);
  return lines.map((l) => `> ${l}`).join('  \n') + '\n\n';
}

/** Table with the family support of the direct children of a node. */
function familyMatrix(node, infoOf, allFamilies, urlOf) {
  const rows = node.children
    .filter((c) => c.repo && infoOf(c.repo).families.length)
    .sort(compareNodes);
  if (!rows.length) return '';
  const columns = allFamilies.filter((f) => rows.some((r) => infoOf(r.repo).families.includes(f)));
  const lines = [
    '',
    '## Family support',
    '',
    `| | ${columns.map(familyName).join(' | ')} |`,
    `|---|${columns.map(() => ':---:').join('|')}|`,
    ...rows.map((r) => {
      const supported = infoOf(r.repo).families;
      return `| [${r.label}](${urlOf(r)}) | ${columns.map((f) => (supported.includes(f) ? '✅' : '—')).join(' | ')} |`;
    }),
    '',
  ];
  return lines.join('\n');
}

function orderIndex(node) {
  const i = ORDER.indexOf(node.segments[node.segments.length - 1]);
  return i === -1 ? 1000 : i + 10;
}

function compareNodes(a, b) {
  return orderIndex(a) - orderIndex(b) || a.label.localeCompare(b.label, 'en', {numeric: true});
}

async function writePage(file, {title, label, position, editUrl}, body) {
  const front = [
    '---',
    `title: ${JSON.stringify(title)}`,
    `sidebar_label: ${JSON.stringify(label)}`,
    `sidebar_position: ${position}`,
    `custom_edit_url: ${editUrl}`,
    '---',
    '',
    // .md files are parsed as CommonMark (see markdown.format in docusaurus.config.ts),
    // so this is a plain HTML comment.
    `<!-- ${GENERATED_MARKER}. Do not edit here. -->`,
    '',
  ].join('\n');
  await mkdir(path.dirname(file), {recursive: true});
  await writeFile(file, front + body);
}

async function main() {
  // 1. Collect everything the layout depends on. Any failure skips the sync.
  const repos = (await listRepos()).filter((r) => !IGNORE.has(r)).sort((a, b) => a.localeCompare(b));
  const infos = await mapLimit(repos, 5, async (repo) => ({
    repo,
    readmes: nestedReadmes(await listFiles(repo)),
    families: await listFamilies(repo),
  }));
  const infoOf = (repo) => infos.find((i) => i.repo === repo);
  const allFamilies = [...new Set(infos.flatMap((i) => i.families))].sort(naturalCompare);

  // 2. Fetch the main README of every repository; repositories without one only act as categories.
  const readmes = new Map();
  const missing = [];
  await Promise.all(
    infos.map(async ({repo}) => {
      const md = await fetchReadme(repo);
      if (md === null) missing.push(repo);
      else readmes.set(repo, md);
    }),
  );
  const documented = infos.filter((i) => readmes.has(i.repo));

  // 3. Build the tree and decide which nodes become folders.
  const {nodes, get} = buildTree(documented);
  for (const {repo, readmes: nested} of documented) {
    const node = get(segmentsOf(repo));
    node.nested = nested;
    node.files = REPO_OPTIONS[repo]?.files ?? [];
  }
  const hasChildren = (n) => n.children.length > 0 || n.nested.length > 0 || n.files.length > 0;
  const dirOf = (n) => path.join(DOCS, ...n.key.split('/'));
  const fileOf = (n) => (hasChildren(n) ? path.join(dirOf(n), 'index.md') : `${dirOf(n)}.md`);
  const urlOf = (n) => `/docs/${n.key}`;
  for (const n of nodes.values()) n.title = titleOf(n);

  const written = new Set();
  const write = async (file, ...args) => {
    written.add(file);
    await writePage(file, ...args);
  };

  // 4. Write the pages.
  for (const node of [...nodes.values()].sort((a, b) => a.key.localeCompare(b.key))) {
    if (!node.repo) {
      // Plain category without a page of its own.
      const file = path.join(dirOf(node), '_category_.json');
      await mkdir(dirOf(node), {recursive: true});
      await writeFile(file, JSON.stringify({label: node.label, position: orderIndex(node)}) + '\n');
      written.add(file);
      continue;
    }
    const {repo} = node;
    const info = infoOf(repo);
    const options = REPO_OPTIONS[repo] ?? {};
    const body =
      familyBanner(repo, info.families, allFamilies) +
      transform(readmes.get(repo), repo, options.replace) +
      familyMatrix(node, infoOf, allFamilies, urlOf);
    await write(
      fileOf(node),
      {
        title: node.title, label: node.label, position: orderIndex(node),
        editUrl: `https://github.com/${ORG}/${repo}/edit/HEAD/README.md`,
      },
      body,
    );

    // Further documentation of the same repository, listed below its main page.
    const banner = familyBanner(repo, info.families, allFamilies);
    let position = 200;
    for (const f of node.files) {
      const md = await fetchReadme(repo, f.source);
      if (md === null) {
        missing.push(`${repo}/${f.source}`);
        continue;
      }
      await write(
        path.join(dirOf(node), `${f.file}.md`),
        {title: f.title, label: f.title, position: position++, editUrl: `https://github.com/${ORG}/${repo}/edit/HEAD/${f.source}`},
        transform(md, repo, f.replace, '', f.replaceAfter),
      );
    }
    position = 300;
    for (const {dir, file: source} of node.nested) {
      const md = await fetchReadme(repo, source);
      if (md === null) {
        missing.push(`${repo}/${source}`);
        continue;
      }
      // Prefer the first heading of the README over the bare directory name.
      const heading = /^#\s+(.+?)\s*#*\s*$/m.exec(md.replace(/\r\n/g, '\n'));
      const title = heading ? heading[1].replace(/[`*_]/g, '').trim() : dir;
      await write(
        path.join(dirOf(node), `${slug(dir)}.md`),
        {title, label: title, position: position++, editUrl: `https://github.com/${ORG}/${repo}/edit/HEAD/${source}`},
        banner + transform(md, repo, [], dir),
      );
    }
  }

  await removeStale(written);

  console.log(`Synced ${written.size} pages.`);
  if (missing.length) console.log(`No README found for: ${missing.join(', ')}`);
}

try {
  await main();
} catch (err) {
  console.warn(`Documentation sync skipped, the committed pages stay as they are (${err.message}).`);
}
